# Generated by Django 3.2.9 on 2021-12-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDropDown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=70)),
                ('value_data', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_date', models.DateField(null=True)),
                ('notice_date', models.DateField(null=True)),
                ('hearing_date', models.DateField(null=True)),
                ('commission_application_number', models.CharField(default='', max_length=70)),
                ('commission_case_number', models.CharField(default='', max_length=70)),
                ('commission_file_number', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_date', models.DateField()),
                ('appeal_date_receive', models.DateField()),
                ('appeal_application_number', models.CharField(default='', max_length=70)),
                ('appeal_reason', models.CharField(blank=True, default='', max_length=100)),
                ('appeal_endorsement', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_number', models.BigIntegerField()),
                ('name', models.CharField(default='', max_length=70)),
                ('of_name', models.CharField(default='', max_length=5)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('mobilenumber', models.CharField(blank=True, default='', max_length=12)),
                ('date_receive', models.DateField(blank=True, null=True)),
                ('is_svu', models.CharField(default=False, max_length=70)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('endorsement_date', models.DateField(blank=True, null=True)),
                ('endorsement', models.CharField(blank=True, default='', max_length=100)),
                ('application_related', models.CharField(blank=True, default='', max_length=100)),
                ('address_transmitted', models.CharField(blank=True, default='', max_length=100)),
                ('commission_appeal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.commissionappeal')),
                ('first_appeal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.firstappeal')),
            ],
        ),
    ]
