# Generated by Django 3.2.9 on 2021-12-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_application_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdropdown',
            name='type',
        ),
    ]
