# Generated by Django 3.2.9 on 2022-01-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_remove_applicationdropdown_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='of_name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
