# Generated by Django 3.2.9 on 2022-03-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_auto_20220109_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionappeal',
            name='commission_endorsement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
